# Generated by Django 3.1 on 2020-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('hu', 'Hungarian'), ('ch', 'Chinese')], default='en', help_text='Choose language', max_length=2)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a language', to='catalog.Language'),
        ),
    ]
